import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen overflow-hidden`}
      >
        {/* Toaster */}

        {/* Header */}
        <header className="border-b sticky z-50 bg-white top-0">
          <Header />
        </header>

        <div className="bg-[#f4f2ed] flex-1 w-full">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
